In [71]:
import numpy as np
import scipy.io

In [72]:
# mat = scipy.io.loadmat('Feature_base_fft.mat')
mat_old = scipy.io.loadmat('Feature.mat')
mat = scipy.io.loadmat('Feature_all_sig.mat')

In [73]:
mat_old

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Fri Nov 27 23:42:49 2020',
 '__version__': '1.0',
 '__globals__': [],
 'Feature': array([[14.7646175 , 76.44940481, -0.09987319, ...,  3.01590418,
          3.03984896,  0.5339    ],
        [16.7558975 , 63.42631429, -0.48693601, ...,  3.04590641,
          3.06949449,  0.626175  ],
        [16.1851075 , 65.2616275 , -0.39036518, ...,  2.71312949,
          2.7337946 ,  0.6015    ],
        ...,
        [16.5925425 , 70.75470316, -0.19483653, ...,  2.47999598,
          2.49331655,  0.55515   ],
        [14.5753925 , 69.74228109,  0.34308477, ...,  2.01043574,
          2.02381469,  0.41765   ],
        [13.8604525 , 68.58917653,  0.56744136, ...,  1.81394632,
          1.82552724,  0.36535   ]])}

In [74]:
Feature = mat['Feature_all_sig']
Feature.shape

(2480, 33)

In [75]:
# mat['Feature_base_fft'].shape

In [76]:
CVD     = 1252
non_CVD = 1228

In [77]:
Y = np.zeros((CVD+non_CVD,1))
Y[:CVD] = 1

In [78]:
import sklearn
from sklearn import linear_model
from sklearn.model_selection import train_test_split

reg = linear_model.LinearRegression()
X_train, X_test, Y_train, Y_test = train_test_split(mat['Feature_all_sig'], Y, test_size=0.2, random_state=109)
# X_train, X_test, Y_train, Y_test = train_test_split(mat_old['Feature'], Y, test_size=0.2, random_state=109)

In [79]:
Y_train.shape

(1984, 1)

In [80]:
Y_test.shape

(496, 1)

In [81]:
reg.fit(X_train,Y_train)

LinearRegression()

In [82]:
reg.coef_

array([[-7.67764597e-03,  5.71933505e-03, -5.96125703e+00,
        -7.92673636e-02, -3.23425797e-02, -1.53951478e-03,
         2.73256771e-01,  6.58294366e+00,  2.42578803e-02,
         2.06058630e+00,  8.08761784e-01,  2.56723330e-02,
        -4.52691463e+00, -8.74449258e-01, -1.10516199e-02,
        -5.38170671e-01,  2.96132256e-02,  5.91021496e-02,
        -2.58357091e+00,  1.35715705e+00,  7.72206793e-02,
        -2.88085139e+00, -6.87153580e-01,  2.81325718e-01,
         7.42410260e-01,  2.24322686e+00,  5.62940143e-01,
        -4.46953370e+01, -6.26333677e-01, -5.58059986e-01,
        -7.44745824e-02, -5.70606888e-03,  2.81831631e+00]])

In [83]:
reg.intercept_

array([8.58515235])

In [84]:
reg.predict(X_test)

array([[ 5.72327392e-01],
       [ 4.24981678e-01],
       [-4.67900863e-02],
       [ 1.25181976e-01],
       [ 1.04765852e+00],
       [ 1.73400174e-01],
       [ 5.65937947e-01],
       [ 4.05940474e-01],
       [ 1.66222921e-01],
       [ 3.18946320e-01],
       [ 7.89729253e-01],
       [-1.76942502e-01],
       [-1.36183724e-01],
       [ 2.29572509e-01],
       [ 1.65286608e-01],
       [ 7.55050966e-01],
       [-7.08842256e-02],
       [ 9.89587036e-01],
       [ 3.79213797e-01],
       [ 9.60707743e-02],
       [ 6.05500940e-02],
       [ 1.29167802e+00],
       [ 9.90087629e-01],
       [-1.54177544e-01],
       [ 7.58856240e-01],
       [ 1.83714086e-01],
       [ 1.27249087e+00],
       [ 1.60110189e-01],
       [ 8.86205031e-01],
       [ 3.47033410e-01],
       [ 8.70399267e-01],
       [ 7.04038060e-01],
       [ 7.61116731e-02],
       [ 2.19712156e-01],
       [ 7.54720236e-01],
       [ 2.01580834e-01],
       [ 2.32354200e-01],
       [ 1.75347558e-01],
       [ 1.5

In [85]:
Y_pred = np.round(reg.predict(X_test))

In [86]:
np.sum(Y_pred==Y_test) / len(Y_test)

0.8729838709677419

In [87]:
Y_pred

array([[ 1.],
       [ 0.],
       [-0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [-0.],
       [-0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [-0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [-0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 2.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [-0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [-0.],
       [ 0.],
       [ 1.],
       [ 1.],
      

In [88]:
CVD     = 1252
non_CVD = 1228
Y = np.zeros((CVD+non_CVD,1))
Y[:CVD] = 1

In [89]:
X_train1, X_test1, Y_train1, Y_test1 = train_test_split(X_train, Y_train, test_size=0.4, random_state=109)

In [90]:
reg.predict(X_test1)

array([[ 0.39608313],
       [ 1.22955991],
       [ 0.14008848],
       [ 0.31609116],
       [ 0.56759093],
       [ 0.46241036],
       [ 0.18893116],
       [ 0.76729344],
       [-0.08584601],
       [ 0.11544236],
       [ 0.39294014],
       [ 1.11238003],
       [ 0.33266676],
       [ 0.47903056],
       [ 0.13733414],
       [ 0.15448087],
       [ 0.50733326],
       [ 0.1355739 ],
       [ 0.32141342],
       [ 0.283834  ],
       [ 0.30072414],
       [ 0.71714317],
       [ 0.4582785 ],
       [-0.13015914],
       [ 0.13467242],
       [-0.0041155 ],
       [ 0.21071777],
       [ 0.50886493],
       [ 0.15229813],
       [ 0.83428086],
       [ 0.87865866],
       [ 0.40148171],
       [ 0.24890336],
       [ 0.37505754],
       [ 1.15878609],
       [ 0.06322711],
       [ 0.47218307],
       [ 0.44949811],
       [ 0.56836707],
       [-0.18235464],
       [ 0.12604156],
       [ 0.54233507],
       [ 0.15944382],
       [ 0.81917816],
       [ 0.16947043],
       [ 0

In [91]:
Y_pred = np.round(reg.predict(X_test1))

In [92]:
print(Y_pred.shape, Y_test1.shape)

(794, 1) (794, 1)


In [93]:
1 - np.sum(abs(Y_pred-Y_test1)) / Y_pred.shape[0]

0.8790931989924433