In [1]:
import tensorflow as tf
tf.compat.v1.enable_eager_execution()
import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
# Choose GPU to use
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID";

# The GPU ID to use, usually either "0" or "1"
os.environ["CUDA_VISIBLE_DEVICES"]="0";

Config=tf.compat.v1.ConfigProto(allow_soft_placement=True)
Config.gpu_options.allow_growth=True

In [3]:
Img_CVD     = 'C:\\Users\\Haoti\\.spyder-py3\\CS760_Final_Project\\COVID\\Covid' + ' (1)' + '.png'
Img_non_CVD = 'C:\\Users\\Haoti\\.spyder-py3\\CS760_Final_Project\\non-COVID\\Non-Covid' + ' (1)' + '.png'

In [4]:
import PIL
print('Pillow Version:', PIL.__version__)

Pillow Version: 7.2.0


In [5]:
# from PIL import Image
# image = Image.open(Img_CVD)

In [6]:
from matplotlib import image
image1 = image.imread(Img_CVD)
image2 = image.imread(Img_non_CVD)

In [7]:
print(image1.shape)

(202, 256, 3)


In [8]:
print(image2.shape)

(229, 321, 4)


In [9]:
# print(image1)

In [10]:
# print(image2)

In [11]:
Img_CVD_path     = 'C:\\Users\\Haoti\\.spyder-py3\\CS760_Final_Project\\COVID\\'
Img_non_CVD_path = 'C:\\Users\\Haoti\\.spyder-py3\\CS760_Final_Project\\non-COVID\\'
import os, os.path
list_COVID     = os.listdir(Img_CVD_path)
list_non_COVID = os.listdir(Img_non_CVD_path)
N_COVID     = len(list_COVID)
N_non_COVID = len(list_non_COVID)
print('Number of Covid files is', N_COVID)
print('Number of non Covid files is', N_non_COVID)

Number of Covid files is 1252
Number of non Covid files is 1229


In [12]:
L_COVID     = np.zeros((N_COVID, 3))
L_non_COVID = np.zeros((N_non_COVID, 3))

for i in range(N_COVID):
    image_COVID = image.imread(Img_CVD_path + 'Covid (' + str(i+1) + ').png')
    L_COVID[i,:] = image_COVID.shape
    
for j in range(N_non_COVID):
    if j+1 < 151:
        image_non_COVID  = image.imread(Img_non_CVD_path + 'Non-Covid (' + str(j+1) + ').png')
    elif j+1 > 151:
        image_non_COVID  = image.imread(Img_non_CVD_path + 'Non-Covid (' + str(j+1) + ').png')
    
    L_non_COVID[j,:] = image_non_COVID.shape

In [14]:
X_COVID = np.max(L_COVID[:,0])
Y_COVID = np.max(L_COVID[:,1])
Z_COVID = np.max(L_COVID[:,2])

X_non_COVID = np.max(L_non_COVID[:,0])
Y_non_COVID = np.max(L_non_COVID[:,1])
Z_non_COVID = np.max(L_non_COVID[:,2])

In [15]:
print(X_COVID, Y_COVID, Z_COVID, X_non_COVID, Y_non_COVID, Z_non_COVID)

408.0 534.0 4.0 416.0 502.0 4.0


In [16]:
L_COVID[0,:]

array([202., 256.,   3.])

In [17]:
L_COVID[1,:]

array([254., 342.,   3.])

In [18]:
L_COVID[2,:]

array([254., 342.,   3.])

In [19]:
L_COVID[3,:]

array([260., 365.,   3.])

In [20]:
L_COVID[300,:]

array([313., 421.,   3.])

In [21]:
L_non_COVID[0,:]

array([229., 321.,   4.])

In [22]:
# Resizing Image into same size (one sample)
from PIL import Image
im = Image.open(Img_CVD)
im.show()
resized_im = im.resize((int(Y_COVID), int(Y_COVID)), resample=3, reducing_gap=None)
resized_im.show()

In [23]:
# Resizing Image into same size (all sample)
from PIL import Image

Img_CVD_path_1     = 'C:\\Users\\Haoti\\.spyder-py3\\CS760_Final_Project\\COVID-new-1\\'
Img_non_CVD_path_1 = 'C:\\Users\\Haoti\\.spyder-py3\\CS760_Final_Project\\non-COVID-new-1\\'

for i in range(N_COVID):
    image_COVID = Image.open(Img_CVD_path + 'Covid (' + str(i+1) + ').png')
    image_COVID = image_COVID.resize((int(200), int(200)), resample=3, reducing_gap=None)
    image_COVID = image_COVID.convert('RGB')
    image_COVID.save(Img_CVD_path_1 + 'Covid (' + str(i+1) + ').png')

In [24]:
for j in range(N_non_COVID):
    if j+1 < 151:
        image_non_COVID  = Image.open(Img_non_CVD_path + 'Non-Covid (' + str(j+1) + ').png')
        image_non_COVID  = image_non_COVID.resize((int(200), int(200)), resample=3, reducing_gap=None)
        image_non_COVID  = image_non_COVID.convert('RGB')
        image_non_COVID.save(Img_non_CVD_path_1 + 'Non-Covid (' + str(j+1) + ').png')
        
    elif j+1 > 151:
        image_non_COVID  = Image.open(Img_non_CVD_path + 'Non-Covid (' + str(j+1) + ').png')
        image_non_COVID  = image_non_COVID.resize((int(200), int(200)), resample=3, reducing_gap=None)
        image_non_COVID  = image_non_COVID.convert('RGB')
        image_non_COVID.save(Img_non_CVD_path_1 + 'Non-Covid (' + str(j) + ').png')

In [38]:
# Reload Image data from new folder

In [25]:
print(image_non_COVID)

<PIL.Image.Image image mode=RGB size=200x200 at 0x177A4DD1C50>
